[2024-10-24T01:12:22.245+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-10-25T08:00:00+00:00 [queued]>
[2024-10-24T01:12:22.296+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-10-25T08:00:00+00:00 [queued]>
[2024-10-24T01:12:22.297+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2024-10-24T01:12:22.381+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-10-25 08:00:00+00:00
[2024-10-24T01:12:22.414+0000] {standard_task_runner.py:57} INFO - Started process 242 to run task
[2024-10-24T01:12:22.420+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-10-25T08:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmpldlvu17d']
[2024-10-24T01:12:22.424+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask Silver
[2024-10-24T01:12:22.569+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-10-25T08:00:00+00:00 [running]> on host de5108c6da1d
[2024-10-24T01:12:22.782+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-25T08:00:00+00:00'
[2024-10-24T01:12:22.868+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T01:12:22.869+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --queue root.default jobs/silver/api_openbrewerydb.py
[2024-10-24T01:16:55.100+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 215, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/local_task_job_runner.py", line 246, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 864, in refresh_from_db
    ti = qry.one_or_none()
         ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:17:24.664+0000] {local_task_job_runner.py:274} WARNING - Recorded pid 978 does not match the current pid 242
[2024-10-24T01:17:24.668+0000] {process_utils.py:131} INFO - Sending 15 to group 242. PIDs of all processes in the group: [268, 964, 242]
[2024-10-24T01:17:24.668+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 242
[2024-10-24T01:17:24.669+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-24T01:17:24.669+0000] {spark_submit.py:654} INFO - Sending kill signal to spark-submit
[2024-10-24T01:17:24.691+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 438, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 492, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-10-24T01:17:24.697+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231025T080000, start_date=20241024T011723, end_date=20241024T011724
[2024-10-24T01:17:24.713+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task Silver (Task received SIGTERM signal; 242)
[2024-10-24T01:17:24.760+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=268, status='terminated', started='01:12:22') (268) terminated with exit code None
[2024-10-24T01:17:24.761+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=242, status='terminated', exitcode=1, started='01:12:21') (242) terminated with exit code 1
[2024-10-24T01:17:24.761+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=964, status='terminated', started='01:17:20') (964) terminated with exit code None
[2024-10-24T14:26:47.521+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-10-25T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:26:47.529+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-10-25T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-10-25T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:26:47.558+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-10-25T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:26:47.558+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-10-25T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-10-25T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:26:47.587+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-10-25T08:00:00+00:00 [queued]>
[2024-10-24T14:26:47.594+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-10-25T08:00:00+00:00 [queued]>
[2024-10-24T14:26:47.594+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-24T14:26:47.604+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-10-25 08:00:00+00:00
[2024-10-24T14:26:47.608+0000] {standard_task_runner.py:57} INFO - Started process 1501 to run task
[2024-10-24T14:26:47.610+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-10-25T08:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmp32a5pgdl']
[2024-10-24T14:26:47.612+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask Silver
[2024-10-24T14:26:47.657+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-10-25T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:26:47.657+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-10-25T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-10-25T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:26:47.658+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-10-25T08:00:00+00:00 [running]> on host 96f89615839b
[2024-10-24T14:26:47.733+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-25T08:00:00+00:00'
[2024-10-24T14:26:47.743+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T14:26:47.744+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark jobs/silver/api_openbrewerydb.py
[2024-10-24T14:26:50.423+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T14:26:50.425+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T14:26:50.425+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SparkContext: Java version 11.0.25
[2024-10-24T14:26:50.485+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T14:26:50.582+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO ResourceUtils: ==============================================================
[2024-10-24T14:26:50.582+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T14:26:50.583+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO ResourceUtils: ==============================================================
[2024-10-24T14:26:50.583+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T14:26:50.606+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T14:26:50.621+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T14:26:50.621+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T14:26:50.669+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T14:26:50.669+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T14:26:50.670+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T14:26:50.670+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T14:26:50.671+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T14:26:50.919+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO Utils: Successfully started service 'sparkDriver' on port 35657.
[2024-10-24T14:26:50.943+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T14:26:50.976+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:50 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T14:26:51.004+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T14:26:51.005+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T14:26:51.008+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T14:26:51.028+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-715b1110-0ca0-421f-843b-d1706374f50c
[2024-10-24T14:26:51.042+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T14:26:51.057+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T14:26:51.189+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T14:26:51.234+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-24T14:26:51.339+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T14:26:51.385+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.2:7077 after 28 ms (0 ms spent in bootstraps)
[2024-10-24T14:26:51.461+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241024142651-0008
[2024-10-24T14:26:51.464+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241024142651-0008/0 on worker-20241024142308-172.18.0.5-43899 (172.18.0.5:43899) with 2 core(s)
[2024-10-24T14:26:51.466+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO StandaloneSchedulerBackend: Granted executor ID app-20241024142651-0008/0 on hostPort 172.18.0.5:43899 with 2 core(s), 1024.0 MiB RAM
[2024-10-24T14:26:51.473+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46141.
[2024-10-24T14:26:51.473+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO NettyBlockTransferService: Server created on 96f89615839b:46141
[2024-10-24T14:26:51.475+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T14:26:51.494+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 96f89615839b, 46141, None)
[2024-10-24T14:26:51.507+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO BlockManagerMasterEndpoint: Registering block manager 96f89615839b:46141 with 434.4 MiB RAM, BlockManagerId(driver, 96f89615839b, 46141, None)
[2024-10-24T14:26:51.510+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 96f89615839b, 46141, None)
[2024-10-24T14:26:51.513+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241024142651-0008/0 is now RUNNING
[2024-10-24T14:26:51.516+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 96f89615839b, 46141, None)
[2024-10-24T14:26:51.800+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:51 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-24T14:26:52.018+0000] {spark_submit.py:524} INFO - Hello from Spark!
[2024-10-24T14:26:52.020+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-24T14:26:52.030+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO SparkUI: Stopped Spark web UI at http://96f89615839b:4040
[2024-10-24T14:26:52.035+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-24T14:26:52.039+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-24T14:26:52.060+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-24T14:26:52.077+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO MemoryStore: MemoryStore cleared
[2024-10-24T14:26:52.078+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO BlockManager: BlockManager stopped
[2024-10-24T14:26:52.087+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-24T14:26:52.090+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-24T14:26:52.100+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO SparkContext: Successfully stopped SparkContext
[2024-10-24T14:26:52.419+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO ShutdownHookManager: Shutdown hook called
[2024-10-24T14:26:52.420+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO ShutdownHookManager: Deleting directory /tmp/spark-5bad6119-4600-4b1c-8d60-c0ae732800bc
[2024-10-24T14:26:52.423+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO ShutdownHookManager: Deleting directory /tmp/spark-31f41cdb-4c77-496b-b8f3-b276f021f4d2/pyspark-6a2dbbcf-8b9b-47d1-aaa1-124e274dc6cc
[2024-10-24T14:26:52.426+0000] {spark_submit.py:524} INFO - 24/10/24 14:26:52 INFO ShutdownHookManager: Deleting directory /tmp/spark-31f41cdb-4c77-496b-b8f3-b276f021f4d2
[2024-10-24T14:26:52.511+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231025T080000, start_date=20241024T142647, end_date=20241024T142652
[2024-10-24T14:26:52.560+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-10-24T14:26:52.606+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
