[2024-10-24T01:12:28.616+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-03T08:00:00+00:00 [queued]>
[2024-10-24T01:12:28.646+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-03T08:00:00+00:00 [queued]>
[2024-10-24T01:12:28.647+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2024-10-24T01:12:28.728+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-11-03 08:00:00+00:00
[2024-10-24T01:12:28.788+0000] {standard_task_runner.py:57} INFO - Started process 765 to run task
[2024-10-24T01:12:28.838+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-11-03T08:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmp_8pw_yah']
[2024-10-24T01:12:28.841+0000] {standard_task_runner.py:85} INFO - Job 52: Subtask Silver
[2024-10-24T01:12:29.238+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-03T08:00:00+00:00 [running]> on host de5108c6da1d
[2024-10-24T01:12:29.763+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T08:00:00+00:00'
[2024-10-24T01:12:29.847+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T01:12:29.849+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --queue root.default jobs/silver/api_openbrewerydb.py
[2024-10-24T01:13:28.448+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 215, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/local_task_job_runner.py", line 246, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 864, in refresh_from_db
    ti = qry.one_or_none()
         ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-10-24T01:17:19.010+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to scheduled. Terminating instance.
[2024-10-24T01:17:19.145+0000] {process_utils.py:131} INFO - Sending 15 to group 765. PIDs of all processes in the group: [771, 765]
[2024-10-24T01:17:19.229+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 765
[2024-10-24T01:17:19.331+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-24T01:17:19.341+0000] {spark_submit.py:654} INFO - Sending kill signal to spark-submit
[2024-10-24T01:17:19.580+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 438, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 492, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-10-24T01:17:19.623+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231103T080000, start_date=20241024T011228, end_date=20241024T011719
[2024-10-24T01:17:19.742+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 52 for task Silver (Task received SIGTERM signal; 765)
[2024-10-24T01:17:19.870+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=765, status='terminated', exitcode=1, started='01:12:28') (765) terminated with exit code 1
[2024-10-24T01:17:19.880+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=771, status='terminated', started='01:12:29') (771) terminated with exit code None
[2024-10-24T14:28:52.957+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-03T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:28:52.965+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-03T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-03T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:28:53.002+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-03T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:28:53.002+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-03T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-03T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:28:53.030+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-03T08:00:00+00:00 [queued]>
[2024-10-24T14:28:53.037+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-03T08:00:00+00:00 [queued]>
[2024-10-24T14:28:53.037+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-24T14:28:53.046+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): Silver> on 2023-11-03 08:00:00+00:00
[2024-10-24T14:28:53.051+0000] {standard_task_runner.py:57} INFO - Started process 4376 to run task
[2024-10-24T14:28:53.053+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_openbrewerydb_to_silver_gold', 'Silver', 'scheduled__2023-11-03T08:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/api_openbrewerydb_to_silver.py', '--cfg-path', '/tmp/tmppk0a_axm']
[2024-10-24T14:28:53.054+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask Silver
[2024-10-24T14:28:53.100+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-03T08:00:00+00:00/task_id=Silver permission to 509
[2024-10-24T14:28:53.100+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-03T08:00:00+00:00/task_id=Silver permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=api_openbrewerydb_to_silver_gold/run_id=scheduled__2023-11-03T08:00:00+00:00/task_id=Silver'
[2024-10-24T14:28:53.100+0000] {task_command.py:415} INFO - Running <TaskInstance: api_openbrewerydb_to_silver_gold.Silver scheduled__2023-11-03T08:00:00+00:00 [running]> on host 96f89615839b
[2024-10-24T14:28:53.176+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rodrigo Araujo' AIRFLOW_CTX_DAG_ID='api_openbrewerydb_to_silver_gold' AIRFLOW_CTX_TASK_ID='Silver' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T08:00:00+00:00'
[2024-10-24T14:28:53.186+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-10-24T14:28:53.187+0000] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark jobs/silver/api_openbrewerydb.py
[2024-10-24T14:28:55.976+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:55 INFO SparkContext: Running Spark version 3.5.3
[2024-10-24T14:28:55.979+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:55 INFO SparkContext: OS info Linux, 5.15.0-124-generic, amd64
[2024-10-24T14:28:55.979+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:55 INFO SparkContext: Java version 11.0.25
[2024-10-24T14:28:56.033+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-24T14:28:56.111+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO ResourceUtils: ==============================================================
[2024-10-24T14:28:56.112+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-24T14:28:56.112+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO ResourceUtils: ==============================================================
[2024-10-24T14:28:56.113+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SparkContext: Submitted application: IngestaoSilver
[2024-10-24T14:28:56.133+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-24T14:28:56.146+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO ResourceProfile: Limiting resource is cpu
[2024-10-24T14:28:56.147+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-24T14:28:56.193+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SecurityManager: Changing view acls to: ***
[2024-10-24T14:28:56.193+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SecurityManager: Changing modify acls to: ***
[2024-10-24T14:28:56.194+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SecurityManager: Changing view acls groups to:
[2024-10-24T14:28:56.194+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SecurityManager: Changing modify acls groups to:
[2024-10-24T14:28:56.195+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-24T14:28:56.412+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO Utils: Successfully started service 'sparkDriver' on port 37857.
[2024-10-24T14:28:56.438+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SparkEnv: Registering MapOutputTracker
[2024-10-24T14:28:56.469+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-24T14:28:56.488+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-24T14:28:56.489+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-24T14:28:56.492+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-24T14:28:56.511+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a3e0315d-296e-464b-8135-061d7bd89ccb
[2024-10-24T14:28:56.524+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-24T14:28:56.538+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-24T14:28:56.685+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-24T14:28:56.742+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-24T14:28:56.862+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-24T14:28:56.912+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.2:7077 after 27 ms (0 ms spent in bootstraps)
[2024-10-24T14:28:56.993+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241024142856-0026
[2024-10-24T14:28:56.995+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241024142856-0026/0 on worker-20241024142308-172.18.0.5-43899 (172.18.0.5:43899) with 2 core(s)
[2024-10-24T14:28:56.999+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:56 INFO StandaloneSchedulerBackend: Granted executor ID app-20241024142856-0026/0 on hostPort 172.18.0.5:43899 with 2 core(s), 1024.0 MiB RAM
[2024-10-24T14:28:57.008+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44657.
[2024-10-24T14:28:57.009+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO NettyBlockTransferService: Server created on 96f89615839b:44657
[2024-10-24T14:28:57.013+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-24T14:28:57.032+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 96f89615839b, 44657, None)
[2024-10-24T14:28:57.041+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO BlockManagerMasterEndpoint: Registering block manager 96f89615839b:44657 with 434.4 MiB RAM, BlockManagerId(driver, 96f89615839b, 44657, None)
[2024-10-24T14:28:57.043+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241024142856-0026/0 is now RUNNING
[2024-10-24T14:28:57.045+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 96f89615839b, 44657, None)
[2024-10-24T14:28:57.047+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 96f89615839b, 44657, None)
[2024-10-24T14:28:57.360+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-24T14:28:57.683+0000] {spark_submit.py:524} INFO - Hello from Spark!
[2024-10-24T14:28:57.684+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-24T14:28:57.702+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO SparkUI: Stopped Spark web UI at http://96f89615839b:4040
[2024-10-24T14:28:57.712+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-24T14:28:57.718+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-24T14:28:57.748+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-24T14:28:57.772+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO MemoryStore: MemoryStore cleared
[2024-10-24T14:28:57.773+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO BlockManager: BlockManager stopped
[2024-10-24T14:28:57.785+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-24T14:28:57.790+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-24T14:28:57.804+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO SparkContext: Successfully stopped SparkContext
[2024-10-24T14:28:57.985+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO ShutdownHookManager: Shutdown hook called
[2024-10-24T14:28:57.986+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-91d3404e-73ca-4d3a-9733-0e9e7a12557f
[2024-10-24T14:28:57.991+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-95759061-f52d-4d46-a519-626bd747391d/pyspark-e6e8b575-86b9-48c4-a8e3-d57e13162dbe
[2024-10-24T14:28:57.996+0000] {spark_submit.py:524} INFO - 24/10/24 14:28:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-95759061-f52d-4d46-a519-626bd747391d
[2024-10-24T14:28:58.091+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=api_openbrewerydb_to_silver_gold, task_id=Silver, execution_date=20231103T080000, start_date=20241024T142853, end_date=20241024T142858
[2024-10-24T14:28:58.123+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-10-24T14:28:58.159+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
